# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-28 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0005_auto_20170410_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='enrollment',
            field=models.CharField(choices=[('default', 'Enroll Request'), ('open', 'Open Enrollment')], max_length=32),
        ),
    ]
