# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-04 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0007_alter_profile_activation_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='snippet',
            field=models.TextField(blank=True),
        ),
    ]
