# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-08 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0008_auto_20170804_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='enable_chat',
            field=models.BooleanField(default=False, verbose_name='Enable/Disable Chat'),
        ),
    ]
