# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-23 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', 'default_grading_system'),
        ('yaksh', '0010_auto_20180226_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrangeTestCase',
            fields=[
                ('testcase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='yaksh.TestCase')),
                ('options', models.TextField(default=None)),
            ],
            bases=('yaksh.testcase',),
        ),
        migrations.CreateModel(
            name='TestCaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.TextField()),
                ('answer_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_paper', to='yaksh.AnswerPaper')),
            ],
        ),
        migrations.RenameField(
            model_name='coursestatus',
            old_name='total_marks',
            new_name='percentage',
        ),
        migrations.AddField(
            model_name='course',
            name='grading_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grades.GradingSystem'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='shuffle_testcases',
            field=models.BooleanField(default=True, verbose_name='Shuffle testcase for each user'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('mcq', 'Single Correct Choice'), ('mcc', 'Multiple Correct Choices'), ('code', 'Code'), ('upload', 'Assignment Upload'), ('integer', 'Answer in Integer'), ('string', 'Answer in String'), ('float', 'Answer in Float'), ('arrange', 'Arrange in Correct Order')], max_length=24),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='weightage',
            field=models.FloatField(default=100, help_text='Will be considered as percentage'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='type',
            field=models.CharField(choices=[('standardtestcase', 'Standard Testcase'), ('stdiobasedtestcase', 'StdIO Based Testcase'), ('mcqtestcase', 'MCQ Testcase'), ('hooktestcase', 'Hook Testcase'), ('integertestcase', 'Integer Testcase'), ('stringtestcase', 'String Testcase'), ('floattestcase', 'Float Testcase'), ('arrangetestcase', 'Arrange Testcase')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='testcaseorder',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaksh.Question'),
        ),
    ]
