# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0011_release_0_8_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Basic, Advanced, Intermediate', 'Basic, Advanced, Intermediate')], default='Basic', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='Unknown', max_length=128),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_between_attempts',
            field=models.FloatField(default=0.0, verbose_name='Time Between Quiz Attempts in hours'),
        ),
    ]
