# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-01 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0012_auto_20180529_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='EasyStandardTestCase',
            fields=[
                ('testcase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='yaksh.TestCase')),
                ('function_name', models.TextField()),
                ('typeof_var', models.CharField(max_length=50)),
                ('operator', models.CharField(max_length=24)),
                ('input_vals', models.CharField(max_length=50)),
                ('output_vals', models.CharField(max_length=24)),
                ('test_case', models.TextField(blank=True)),
            ],
            bases=('yaksh.testcase',),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='type',
            field=models.CharField(choices=[('standardtestcase', 'Standard Testcase'), ('stdiobasedtestcase', 'StdIO Based Testcase'), ('mcqtestcase', 'MCQ Testcase'), ('hooktestcase', 'Hook Testcase'), ('integertestcase', 'Integer Testcase'), ('stringtestcase', 'String Testcase'), ('floattestcase', 'Float Testcase'), ('arrangetestcase', 'Arrange Testcase'), ('easy_standardtestcase', 'Easy Standard Testcase')], max_length=24, null=True),
        ),
    ]
