# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-01 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0013_auto_20180601_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easystandardtestcase',
            name='typeof_var',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
