# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-07 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0013_release_0_9_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentupload',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yaksh.Course'),
        ),
    ]
