# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-05 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0017_auto_20180605_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easystandardtestcase',
            name='operator',
            field=models.CharField(max_length=24),
        ),
    ]
