# Generated by Django 3.0.3 on 2020-06-08 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import yaksh.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yaksh', '0017_release_0_14_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=yaksh.models.get_image_dir, validators=[yaksh.models.validate_image])),
                ('active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('forumbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='yaksh.ForumBase')),
                ('title', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='yaksh.Course')),
            ],
            bases=('yaksh.forumbase',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('forumbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='yaksh.ForumBase')),
                ('post_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='yaksh.Post')),
            ],
            bases=('yaksh.forumbase',),
        ),
    ]
