# Generated by Django 3.0.3 on 2020-05-06 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0018_comment_forumbase_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunit',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_lesson', to='yaksh.Lesson'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_quiz', to='yaksh.Quiz'),
        ),
    ]
