# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-15 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0018_auto_20180605_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='easystandardtestcase',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
