# Generated by Django 3.0.3 on 2020-07-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0019_release_0_20_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='hooktestcase',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='standardtestcase',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stdiobasedtestcase',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
