# Generated by Django 3.0.3 on 2020-05-06 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0019_auto_20200506_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunit',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yaksh.Lesson'),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yaksh.Quiz'),
        ),
    ]
