# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-25 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0020_auto_20180625_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='easystandardtestcase',
            name='typeof_output',
            field=models.CharField(blank=True, choices=[('int', 'int'), ('float', 'float'), ('double', 'double'), ('char', 'char'), ('void', 'void')], max_length=50, null=True),
        ),
    ]
