# Generated by Django 3.0.7 on 2020-09-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0023_release_0_23_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestatus',
            name='certificate',
            field=models.BooleanField(default=False),
        ),
    ]
