# Generated by Django 3.0.7 on 2020-10-07 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import yaksh.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yaksh', '0024_release_0_24_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_path',
            field=models.CharField(blank=True, default=None, help_text='Youtube id, vimeo id, others', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='learningmodule',
            name='check_prerequisite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='check_prerequisite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, default=None, help_text='Please upload video files in mp4, ogv, webm format', max_length=255, null=True, upload_to=yaksh.models.get_file_dir),
        ),
        migrations.CreateModel(
            name='TableOfContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default=0, max_length=100)),
                ('content', models.IntegerField(choices=[(1, 'Topic'), (2, 'Graded Quiz'), (3, 'Exercise'), (4, 'Poll')])),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='yaksh.Course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='yaksh.Lesson')),
            ],
            options={
                'verbose_name_plural': 'Table Of Contents',
            },
        ),
        migrations.CreateModel(
            name='LessonQuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaksh.Answer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('toc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaksh.TableOfContents')),
            ],
        ),
    ]
