# Generated by Django 3.0.7 on 2020-11-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0026_release_0_27_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
