# Generated by Django 3.1.7 on 2026-07-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0030_alter_answerpaper_user_ip_max_len'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='enable_camera',
            field=models.BooleanField(default=True, verbose_name='Enable Camera'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='enable_fullscreen',
            field=models.BooleanField(default=True, verbose_name='Enable Fullscreen'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='enable_microphone',
            field=models.BooleanField(default=True, verbose_name='Enable Microphone'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='enable_multiple_face_detection',
            field=models.BooleanField(default=False, verbose_name='Detect Multiple Faces'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='enable_right_click',
            field=models.BooleanField(default=True, verbose_name='Disable Right Click'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='enable_screenshot_detection',
            field=models.BooleanField(default=False, verbose_name='Detect Print Screen'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='enable_tab_switch',
            field=models.BooleanField(default=True, verbose_name='Detect Tab Switching'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_violations',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='quiz',
            name='safe_browser',
            field=models.BooleanField(default=False, verbose_name='Enable Safe Browser'),
        ),
    ]
