# Generated by Django 3.1.7 on 2026-08-12 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0030_alter_answerpaper_user_ip_max_len'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerpaper',
            name='seb_config_key',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='answerpaper',
            name='seb_user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='answerpaper',
            name='seb_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SEB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('config_file', models.FileField(blank=True, null=True, upload_to='seb_configs/')),
                ('config_key', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seb', to='yaksh.quiz')),
            ],
        ),
    ]
