# Generated by Django 3.1.7 on 2026-07-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0031_auto_20260701_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerpaper',
            name='terminated_by_safe_browser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answerpaper',
            name='violation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answerpaper',
            name='violation_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
