# Generated by Django 3.1.7 on 2026-06-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0031_auto_20260630_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_seb_required',
            field=models.BooleanField(default=False, verbose_name='Require Safe Exam Browser'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='seb_config_file',
            field=models.FileField(blank=True, help_text='Upload the .seb file for automatic student launching', null=True, upload_to='seb_configs/', verbose_name='SEB Config File'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='seb_config_key',
            field=models.CharField(blank=True, help_text='The Config Key Hash generated by SEB Configuration Tool', max_length=255, null=True, verbose_name='SEB Config Key'),
        ),
    ]
