# Generated by Django 3.1.7 on 2026-07-27 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0032_auto_20260702_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeBrowserCapture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='safe_browser_photos/')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('answer_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safe_browser_captures', to='yaksh.answerpaper')),
            ],
        ),
    ]
