# Generated by Django 3.1.7 on 2026-07-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0032_auto_20260630_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='seb_settings',
            field=models.JSONField(blank=True, default=dict, help_text='JSON mapping for dynamically generated SEB configurations.', null=True, verbose_name='SEB Dynamic Settings'),
        ),
    ]
