# Generated by Django 3.1.7 on 2025-12-15 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yaksh', '0033_auto_20251215_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='trophy', help_text="Icon identifier (e.g., 'trophy', 'fire', 'star')", max_length=50)),
                ('color', models.CharField(default='blue', help_text="Color theme (e.g., 'blue', 'green', 'purple')", max_length=20)),
                ('badge_type', models.CharField(help_text="Type of badge (e.g., 'streak', 'challenge', 'course')", max_length=50)),
                ('criteria_type', models.CharField(help_text='Criteria evaluation type', max_length=50)),
                ('criteria_value', models.IntegerField(default=1, help_text='Target value for criteria')),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_challenges_solved', models.IntegerField(default=0)),
                ('challenges_this_week', models.IntegerField(default=0)),
                ('challenges_this_month', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('total_learning_hours', models.FloatField(default=0.0, help_text='Total learning hours')),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('weekly_reset_date', models.DateField(blank=True, null=True)),
                ('monthly_reset_date', models.DateField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Stats',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('lesson_completed', 'Lesson Completed'), ('quiz_completed', 'Quiz Completed'), ('badge_earned', 'Badge Earned'), ('streak_milestone', 'Streak Milestone'), ('course_enrolled', 'Course Enrolled'), ('course_completed', 'Course Completed'), ('comment_posted', 'Comment Posted')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='check', help_text='Icon identifier', max_length=50)),
                ('color', models.CharField(default='blue', help_text='Color theme', max_length=20)),
                ('badge_name', models.CharField(blank=True, help_text='Badge name if activity is badge_earned', max_length=100, null=True)),
                ('related_course_id', models.IntegerField(blank=True, null=True)),
                ('related_lesson_id', models.IntegerField(blank=True, null=True)),
                ('related_quiz_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaksh.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_date'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('challenges_solved', models.IntegerField(default=0)),
                ('time_spent', models.FloatField(default=0.0, help_text='Time in hours')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('courses_accessed', models.ManyToManyField(blank=True, to='yaksh.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Daily Activities',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BadgeProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_progress', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaksh.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
