# Generated by Django 3.1.7 on 2025-12-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0034_badge_badgeprogress_dailyactivity_useractivity_userbadge_userstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_paper',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_direct', to='yaksh.questionpaper'),
        ),
    ]
