# Generated by Django 3.0.7 on 2020-11-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonlog',
            name='current_time',
            field=models.CharField(default='00:00:00', max_length=20),
        ),
        migrations.AddField(
            model_name='tracklesson',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
