# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-31 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_standardtestcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='easy_standardtestcase',
            name='lang',
            field=models.CharField(choices=[(b'python', b'Python'), (b'bash', b'Bash'), (b'c', b'C Language'), (b'cpp', b'C++ Language'), (b'java', b'Java Language'), (b'scilab', b'Scilab')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='easy_standardtestcase',
            name='operator',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
