# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-31 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easy_standardtestcase', '0002_auto_20180531_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='easy_standardtestcase',
            name='typval',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
