# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-31 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easy_standardtestcase', '0003_easy_standardtestcase_typval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='easy_standardtestcase',
            old_name='typval',
            new_name='typeval',
        ),
    ]
