# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-23 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='entity',
        ),
        migrations.AddField(
            model_name='permission',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_permission', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='permission',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='perm_type',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write')], max_length=20),
        ),
    ]
