# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-24 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_auto_20190523_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='team',
            new_name='role',
        ),
    ]
