# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-24 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_auto_20190524_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_team', to='permissions.Team'),
        ),
    ]
