# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-27 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0015_release_0_10_0'),
        ('permissions', '0004_permission_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='courses',
            field=models.ManyToManyField(to='yaksh.Course'),
        ),
    ]
