FROM centos:latest

MAINTAINER FOSSEE <pythonsupport@fossee.in>

RUN yum update -y && \
yum install git python3-pip mariadb-devel sudo java-1.8.0-openjdk java-1.8.0-openjdk-devel gcc make python3-devel -y

RUN mkdir -p /Sites/online_test

COPY . /Sites/online_test

RUN pip3 install -r /Sites/online_test/requirements/requirements-codeserver.txt

COPY docker/Files/Start-codeserver.sh /Sites

WORKDIR /Sites/online_test

RUN mkdir -p yaksh_data/output yaksh_data/data 

EXPOSE 55555

CMD [ "/bin/bash" , "/Sites/Start-codeserver.sh" ]
