FROM ubuntu:16.04

MAINTAINER FOSSEE <pythonsupport@fossee.in>

RUN apt-get update && \
apt-get install -y  software-properties-common && \
echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
add-apt-repository -y ppa:webupd8team/java && \
apt-get update && \
apt-get install -y oracle-java8-installer && \
apt-get install git python3-pip libmysqlclient-dev sudo default-jre default-jdk -y 

VOLUME /Sites/online_test

ADD Files/requirements-* /tmp/

RUN pip3 install -r /tmp/requirements-codeserver.txt && mkdir -p /Sites/online_test/yaksh_data/output /Sites/online_test/yaksh_data/data

WORKDIR /Sites/online_test/yaksh_data

ADD Files/Start-codeserver.sh /Sites

EXPOSE 53579

CMD [ "/bin/bash" , "/Sites/Start-codeserver.sh" ]
