# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-13 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import yaksh.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yaksh', '0008_release_0_7_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('total_marks', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='LearningModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('order', models.IntegerField(default=0)),
                ('check_prerequisite', models.BooleanField(default=True)),
                ('html_data', models.TextField(blank=True, null=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('type', models.CharField(max_length=16)),
                ('check_prerequisite', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('html_data', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=yaksh.models.get_file_dir)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='yaksh.Lesson')),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='language',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='prerequisite',
        ),
        migrations.AddField(
            model_name='answerpaper',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yaksh.Course'),
        ),
        migrations.AddField(
            model_name='question',
            name='min_time',
            field=models.IntegerField(default=0, verbose_name='time in minutes'),
        ),
        migrations.AddField(
            model_name='question',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_exercise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='weightage',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='learningunit',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yaksh.Lesson'),
        ),
        migrations.AddField(
            model_name='learningunit',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yaksh.Quiz'),
        ),
        migrations.AddField(
            model_name='learningmodule',
            name='learning_unit',
            field=models.ManyToManyField(related_name='learning_unit', to='yaksh.LearningUnit'),
        ),
        migrations.AddField(
            model_name='coursestatus',
            name='completed_units',
            field=models.ManyToManyField(related_name='completed_units', to='yaksh.LearningUnit'),
        ),
        migrations.AddField(
            model_name='coursestatus',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaksh.Course'),
        ),
        migrations.AddField(
            model_name='coursestatus',
            name='current_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_unit', to='yaksh.LearningUnit'),
        ),
        migrations.AddField(
            model_name='coursestatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_module',
            field=models.ManyToManyField(related_name='learning_module', to='yaksh.LearningModule'),
        ),
    ]
