# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-26 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0009_auto_20180113_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodule',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_between_attempts',
            field=models.FloatField(verbose_name='Time Between Quiz Attempts in hours'),
        ),
        migrations.AlterUniqueTogether(
            name='answerpaper',
            unique_together=set([('user', 'question_paper', 'attempt_number', 'course')]),
        ),
    ]
