name: Run Tests CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        runs-on: [ubuntu-latest]

        services:
          redis:
            image: redis
            ports:
              - 6379:6379

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Install Scilab, R, firefox and xvfb
              run: |
                sudo apt-get update
                sudo apt-get install -y python3.6 python3.6-venv python3.6-dev
                sudo apt-get update -qq
                sudo apt-get install -y scilab r-base xvfb firefox
                sudo apt-get install -y r-base

            - name: Start xvfb
              run: |
                Xvfb :99 -screen 0 1024x768x24 &
                echo "DISPLAY=:99" >> $GITHUB_ENV
                
            - name: Set up Python 3.6 venv
              run: |
                python3.6 -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt
                pip install -r requirements/requirements-common.txt
                pip install codecov
                python setup.py develop

            - name: Run Django migrations
              run: |
                ./venv/bin/python manage.py makemigrations notifications_plugin
                ./venv/bin/python manage.py makemigrations stats
                ./venv/bin/python manage.py makemigrations
                ./venv/bin/python manage.py migrate auth
                ./venv/bin/python manage.py migrate

            - name: Run tests with coverage and Celery
              run: |
                ./venv/bin/coverage erase
                celery multi start 1 -A online_test worker -B
                ./venv/bin/coverage run -p manage.py test -v 2 yaksh
                ./venv/bin/coverage run -p manage.py test -v 2 stats
                ./venv/bin/coverage run -p manage.py test -v 2 grades
                ./venv/bin/coverage run -p manage.py test -v 2 yaksh.live_server_tests.load_test
                ./venv/bin/coverage run -p manage.py test -v 2 api
                celery multi stop 1
                find . -type f -name "*.pid" -exec rm -f {} \;


            - name: Upload coverage to Codecov
              run: |
                ./venv/bin/coverage combine
                ./venv/bin/coverage report
                codecov

            - name: Generate HTML coverage report
              run: coverage html

            - name: Upload HTML coverage report
              uses: actions/upload-artifact@v4
              with:
                name: htmlcov
                path: htmlcov/
